### ISSUE TITLE
Calling functions on collections of range objects behaves unexpectedly (to me)

### ISSUE THREAD

**Issue by ojw** [disalvjn/faconne#2]
```clojure
(faconne/transform
       [3 2 1 4 5]
       [item]
       [(inc item)])
=> [4 3 2 5 6]
```
Nice, as expected.
```clojure
(faconne/transform
       [3 2 1 4 5]
       [item]
       (apply min [item]))
nil
```

It would be cool if calling functions on cols built this way worked.  No idea how easy/hard to implement, or if there's another good way to do the same.

**Comment by ojw** [comment]
Desired output is `1`, from `(apply min [3 2 1 4 5])`.

**Comment by disalvjn** [comment]
@ojw Do you remember the context for this? It's probably more complicated than this example (since you could just call `(apply min items)` instead of bothering with the transform at all). 

I think it's really a request for reducing logic instead of just merging/concatenating logic.

For example, the following would be nice to express:
```clojure
;; Get the max and min grades for each student across all their courses
(transformer 
   [{:keys [student-name course-name grade]}] 
   {student-name {:max-grade (max [grade]), :min-grade (min [grade])}})

;; Get the course the student has the highest grade in
(transformer 
   [{:keys [student-name course-name grade] :as tuple}]
   {student-name {:course-with-max-grade (:course-name (apply max-key :grade [tuple]))}})
``` 
I'm not sure if I'm a fan of that syntax in particular, but these would be cool to express.

Is stuff like that what you had in mind / do you have anything to add?

**Comment by ojw** [comment]
Yes, I think that's exactly what I was looking for.

What bothers you about the syntax?  I might expect to have to `apply` `max` in your first example, but otherwise it looks the way I would expect.

**Comment by disalvjn** [comment]
1.1.0 (Released today!) implements this.
