### ISSUE TITLE
1.1.0 broke code that worked on 1.0.3

### ISSUE THREAD

**Issue by fmjrey** [disalvjn/faconne#3]
Not had time to investigate but here's the code that broke:
```
  (f/transform (x/parse xml)
               ;; XML:
               ;; <fixtures>
               ;;   <fixture ...>
               ;;     <team .../>
               ;;     <team .../>
               ;;   </fixture>
               ;;   <fixture ...>
               ;;     <team .../>
               ;;     <team .../>
               ;;   </fixture>
               ;;   ...
               ;;   <teams>
               ;;     <team .../>
               ;;     <team .../>
               ;;     ...
               ;;     <team .../>
               ;;   </teams>
               ;; </fixtures>
               {:tag     :fixtures
                :content [{:tag     tag,
                           :attrs   attrs
                           :content [{:tag   :team,
                                      :attrs team1-attrs}
                                     {:tag   :team,
                                      :attrs team2-attrs}]}]}
               ;; What we want
               ;; {:fixtures [{... :teams [{} {}]}
               ;;             {... :teams [{} {}]}
               ;;             {... :teams [{} {}]}
               ;;             ...]
               ;;  :teams [{} {} {} ...]}
               {(case tag
                  :fixture :fixtures
                  :teams :teams)
                (case tag
                  :fixture [(assoc attrs :teams [team1-attrs team2-attrs])]
                  :teams (if team2-attrs ;; nil when we have an odd number of teams
                           [team1-attrs team2-attrs]
                           [team1-attrs]))}))
```
Any advice?

**Comment by fmjrey** [comment]
The output with 1.1.0 is basically containing only one fixture, the last one, and only odd teams. Teams within a fixture are fine.

**Comment by fmjrey** [comment]
Great explanation.
I tried using ```` and `vector` instead of `[]` in vain.
`@` sounds like a good idea then.
Thanks for the quick reply and also for your great lib!

**Comment by ojw** [comment]
Anyone using `@` for `deref` in a faconne range would have to switch to `deref`, right?  I don't know if there are many/any users doing that, but it is something that could also break <1.1.0 code.

One idea might be something like `~@` and have it work like splicing unquote in a macro - so faconne would provide the apply.

But could someone be using backtick quoting forms in faconne expressions?  I guess this would break them.  I would expect that to be less common, but idk.

Idk.

**Comment by fmjrey** [comment]
How about [metadata](https://clojure.org/reference/metadata)?
E.g. `^{:faconne/expand true} [a b]`

**Comment by ojw** [comment]
I really like that... I rarely/never use metadata and have no idea if that use is idiomatic, but I'm into it.

**Comment by fmjrey** [comment]
I think metadata is a good tool for the job: we are tagging elements of a data structure so it can be handled differently by the parser. It's comparable to what the [metadata doc](https://clojure.org/reference/metadata) says in its intro:
> It is used to convey information to the compiler about types, but can also be used by application developers for many purposes, annotating data sources, policy etc.
In our case faconne is the compiler.

It could also help for literal symbols: `^:faconne/literal my-symbol`
It would not work for keywords unfortunately as they can't have metadata.
Maybe literal keywords just need to be quoted since macro expansion preserves the quoting for the macro to pick up on:
```
':k
=> :k
(let [k ':k] (type k))
=> clojure.lang.Keyword
(macroexpand '(let [k ':k] (type k)))
=> (let* [k (quote :k)] (type k))
```

**Comment by disalvjn** [comment]
Thanks @fmjrey for the suggestion, I think metadata is the perfect fit. It lets us easily and idiomatically specify this type of operation, and lets us support other types of operations with a uniform syntax.

I also like changing `(:literal :k)` to `':k` and `(:literal symbol)` to `(^:literal symbol)`, although I'll continue to support the former version. I'll work on getting those into a later release, because this bug needs to be fixed quickly.

I believe we can use unqualified keywords for the metadata (the advantage being that no one has to know how to spell `faconne`), because we're attaching them to structures/symbols whose lifetime is exclusively the transform. They're written as arguments to the transform, and since the transform is a macro, these arguments need to specified inline, not def'd anywhere else. So, those symbols/structures are used _only_ in the arguments to the transform. 

I was playing with the fix yesterday, and I believe it's fairly straightforward. I'll work on getting this released within the next several days.

Thanks again for your help!

**Comment by turtlegrammar** [comment]
Faconne 1.1.1 fixes this.

**Comment by fmjrey** [comment]
I can confirm 1.1.1 now works for me, no need to change any code.
Thanks for the prompt fixing @disalvjn
